# Generated by Django 3.2.13 on 2022-05-31 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pets',
            options={'verbose_name_plural': 'Pets'},
        ),
        migrations.AddField(
            model_name='pets',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
